2016-09-26 16:24:58,691 [Thread-7:140009041196800] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:03:09,468 [Thread-21:140301079410432] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:29:57,563 [Thread-28:139927104132864] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:31:22,375 [Thread-55:139927104132864] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:35:21,272 [Thread-82:139927014602496] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:49:45,301 [Thread-3:140380696127232] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:49:46,534 [Thread-7:140380696127232] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /assets/hostlist/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'assets_hostlist_admin'
2016-09-26 17:49:47,884 [Thread-8:140380696127232] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 17:49:49,145 [Thread-10:140380696127232] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /assets/hostlist/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'assets_hostlist_admin'
2016-09-26 17:49:51,938 [Thread-11:140380696127232] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:15:21,371 [Thread-2:140471953336064] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /assets/hostlist/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 162, in assets_hostlist_admin
    'update':True}
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' update' from 'if update'
2016-09-26 18:15:27,159 [Thread-3:140471953336064] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /assets/hostlist/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 162, in assets_hostlist_admin
    'update':True}
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' update' from 'if update'
2016-09-26 18:16:00,858 [Thread-4:140471953336064] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /assets/hostlist/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 162, in assets_hostlist_admin
    'update':True}
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' update' from 'if update'
2016-09-26 18:22:41,903 [Thread-96:140471868319488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:22:45,292 [Thread-99:140471868319488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:22:46,379 [Thread-102:140471868319488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:22:47,414 [Thread-105:140471868319488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:22:48,647 [Thread-108:140471868319488] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:24:09,770 [Thread-138:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:24:43,309 [Thread-146:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:24:47,508 [Thread-154:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:25:20,814 [Thread-162:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:25:22,692 [Thread-165:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:25:28,069 [Thread-167:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:26:05,896 [Thread-175:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:34:47,711 [Thread-269:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 18:34:55,920 [Thread-273:140471847339776] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-27 09:56:55,522 [Thread-56:139878790149888] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-27 10:02:40,996 [Thread-89:139878800639744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-27 10:02:45,877 [Thread-94:139878800639744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-27 10:02:47,404 [Thread-97:139878800639744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-12-15 12:55:08,683 [Thread-5:140137099413248] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-12-15 12:55:43,746 [Thread-11:140137099413248] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-12-15 13:17:16,570 [Thread-303:140137081423616] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/data/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-12-15 13:34:22,953 [Thread-386:140136864020224] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-12-15 15:57:00,392 [Thread-141:140208029787904] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/root/.virtualenvs/django_1.8.2/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-12-15 16:05:42,785 [Thread-200:140208029787904] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/root/.virtualenvs/django_1.8.2/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-12-15 16:08:31,415 [Thread-232:140208029787904] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/root/.virtualenvs/django_1.8.2/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-12-15 16:49:23,035 [Thread-12:140690412619520] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/root/.virtualenvs/django_1.8.2/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
