2016-09-26 10:01:34,123 [Thread-4:139946878826240] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 11:37:07,636 [Thread-30:140707135280896] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 11:37:09,135 [Thread-32:140707135280896] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 11:37:12,082 [Thread-36:140707135280896] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:02:52,785 [Thread-12:140026364671744] [django.request:170] [base:get_response] [WARNING]- Not Found: /saltcall/paudit_id=9
2016-09-26 13:20:06,466 [Thread-14:139965720672000] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:20:43,964 [Thread-15:139965720672000] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:23:02,198 [Thread-2:140285577262848] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:23:17,302 [Thread-6:139879204701952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:24:35,918 [Thread-2:140731983271680] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:25:19,124 [Thread-2:139910438713088] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:26:57,703 [Thread-2:140568552707840] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:27:29,463 [Thread-6:140547213743872] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:29:57,719 [Thread-6:140578503599872] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:31:49,119 [Thread-19:140355254404864] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:41:22,369 [Thread-10:139972429403904] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:42:02,905 [Thread-2:140481535145728] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:45:18,368 [Thread-6:140452198082304] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 13:53:26,822 [Thread-2:140110272481024] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:03:59,375 [Thread-2:140181010491136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'cmdb_paudit.StartTime' in 'field list'")
2016-09-26 14:04:32,069 [Thread-3:140181010491136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'cmdb_paudit.StartTime' in 'field list'")
2016-09-26 14:04:34,639 [Thread-4:140181010491136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'cmdb_paudit.StartTime' in 'field list'")
2016-09-26 14:04:53,589 [Thread-5:140181010491136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'cmdb_paudit.StartTime' in 'field list'")
2016-09-26 14:07:06,530 [Thread-2:140615969629952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 200, in audit
    'show_lines': Paging(lines, 10, page),
  File "/root/djangoproject/djangoproject/views/views.py", line 132, in Paging
    show_lines = paginator.page(1)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 50, in page
    number = self.validate_number(number)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 86, in _get_num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'django.cmdb_paudit' doesn't exist")
2016-09-26 14:07:23,305 [Thread-3:140615969629952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 378, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 49, in pre_sql_setup
    order_by = self.get_order_by()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 286, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 558, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 591, in _setup_joins
    pieces, opts, alias)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1466, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1391, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'time' into field. Choices are: EndTime, StartTime, action, action_id, detail, id, project, project_id, requester, requester_id, result, status, username, username_id, version
2016-09-26 14:07:25,303 [Thread-4:140615969629952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit
    'link':link
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 378, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 49, in pre_sql_setup
    order_by = self.get_order_by()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 286, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 558, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 591, in _setup_joins
    pieces, opts, alias)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1466, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1391, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'time' into field. Choices are: EndTime, StartTime, action, action_id, detail, id, project, project_id, requester, requester_id, result, status, username, username_id, version
2016-09-26 14:08:35,566 [Thread-11:140149183977216] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:09:16,553 [Thread-32:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 14:09:16,575 [Thread-33:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 14:09:16,595 [Thread-34:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 14:09:16,615 [Thread-35:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 14:09:16,633 [Thread-36:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 14:09:16,652 [Thread-37:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 14:09:16,765 [Thread-39:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 14:09:16,788 [Thread-40:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 14:09:16,810 [Thread-41:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 14:09:16,832 [Thread-42:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 14:09:16,848 [Thread-43:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 14:09:16,864 [Thread-44:140149183977216] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 14:15:01,586 [Thread-10:140029856524032] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:15:31,950 [Thread-11:140029856524032] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:15:52,852 [Thread-12:140029856524032] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:17:02,603 [Thread-11:139863828375296] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:17:31,147 [Thread-11:140240464127744] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:22:43,560 [Thread-2:139912230672128] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /saltcall/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.saltcall didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:36:22,871 [Thread-131:140626082469632] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:38:36,945 [Thread-148:140626082469632] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 15:22:36,256 [Thread-4:140138908317440] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 15:39:24,562 [Thread-28:140453077104384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 15:39:25,530 [Thread-30:140453077104384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-26 15:53:38,652 [Thread-6:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 15:53:38,676 [Thread-7:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 15:53:38,695 [Thread-8:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 15:53:38,716 [Thread-9:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 15:53:38,738 [Thread-10:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 15:53:38,769 [Thread-11:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 15:53:38,849 [Thread-13:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 15:53:38,867 [Thread-14:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 15:53:38,890 [Thread-15:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 15:53:38,907 [Thread-16:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 15:53:38,925 [Thread-17:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-26 15:53:38,944 [Thread-18:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-26 15:53:39,566 [Thread-19:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-26 15:53:39,588 [Thread-20:140421791930112] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
